### ISSUE TITLE
Latest Weights?

### ISSUE THREAD

**Issue by bio-rat** [luwei0917/DynamicBind#4]
Hi Luwei, I have been using your web server for docking to my Alphafold predicted structure but I have have too many of them so I just installed your code to run it local but the result was not as accurate as the web version. Is there a difference between the web server weights and the one published on github?

**Comment by luwei0917** [comment]
Right. the weights here is the one we used for the paper. but we also re-trained the model with more data and more computational resources. Since we were using company's resources to train it, the re-trained model probably should not be openly released. Maybe you could send me an email (luwei0917@gmail.com) about your purpose of use, and we could probably ask for permission from the company.
